export const enum QueueNames {
  FILE_UPLOAD_QUEUE = 'FILE_UPLOAD_QUEUE',
  SEND_MAIL_QUEUE = 'SEND_MAIL_QUEUE',
  GET_TOKEN_DETAIL_QUEUE = 'GET_TOKEN_DETAIL_QUEUE',
  CALCULATING_RARITY_QUEUE = 'CALCULATING_RARITY_QUEUE',
  GET_TOKENS_QUEUE = 'GET_TOKENS_QUEUE',
  WALLET_ASSET_QUEUE = 'WALLET_ASSET_QUEUE',
  OPENSEA_WALLET_CONTRACTS_INFO = 'OPENSEA_WALLET_CONTRACTS_INFO',
  TRENDS_EXPLORER_CALCULATOR = 'TRENDS_EXPLORER_CALCULATOR',
  TRENDS_CLEANER = 'TRENDS_CLEANER',
  CONTRACTS_OPENSEA_RETRIEVING = 'CONTRACTS_OPENSEA_RETRIEVING',
  CONTRACTS_OPENSEA_INFO = 'CONTRACTS_OPENSEA_INFO',
  CONTRACTS_INFO = 'CONTRACTS_INFO',
}
